declare interface ScoringSettings {
  st_ff: number
  pts_allow_7_13: number
  def_st_ff: number
  rec_yd: number
  fum_rec_td: number
  pts_allow_35p: number
  pts_allow_28_34: number
  fum: number
  rush_yd: number
  pass_td: number
  blk_kick: number
  pass_yd: number
  safe: number
  bonus_rush_yd_200: number
  pass_fd: number
  def_td: number
  fgm_50p: number
  def_st_td: number
  bonus_rec_yd_200: number
  fum_rec: number
  rush_2pt: number
  pass_sack: number
  xpm: number
  bonus_pass_yd_300: number
  pts_allow_21_27: number
  fgm_20_29: number
  rush_att: number
  rec_fd: number
  pts_allow_1_6: number
  fum_lost: number
  def_st_fum_rec: number
  int: number
  fgm_0_19: number
  pts_allow_14_20: number
  rec: number
  ff: number
  fgmiss: number
  st_fum_rec: number
  pass_att: number
  rush_fd: number
  rec_2pt: number
  fgm: number
  rush_td: number
  xpmiss: number
  fgm_30_39: number
  rec_td: number
  fgm_yds_over_30: number
  st_td: number
  rec_0_4: number
  pass_2pt: number
  bonus_pass_yd_400: number
  pts_allow_0: number
  pass_int: number
  bonus_rush_yd_100: number
  bonus_rec_yd_100: number
  fgm_40_49: number
  sack: number
}
declare interface Player {
  key: string
  general: any
  passing: any
  scrimmage: any
}
